### PR TITLE
Fix #32

### LINKED ISSUE #32: Reference LICENSE into README

### PR DESCRIPTION
**Pull request by nitishkd**
Added Reference of License into readme

### CODE REVIEW

**Comment by nitishkd** [comment]
@pedrommone I have added reference. Can you please review it? Thanks.

**Comment by nitishkd** [comment]
@pedrommone Thanks for merging my PR. This was my first open source contribution that got merged.

**Comment by pedrommone** [comment]
@nitishkd its always grateful helping the community, huh? Feel fee to take a look at other issues and try something out!

**Comment by nitishkd** [comment]
Sure!

**Pull request merged**
